django_app/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('sns/', include('sns.urls')),
    path('mycalendar/', include('mycalendar.urls')),
]

mycalendar/urls.py
from django.urls import path
from . import views
from .views import edit

app_name = 'mycalendar'
urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),

    path('month_with_schedule/', views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/',
         views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),

    path('month_with_forms/', views.MonthWithFormsCalendar.as_view(), name='month_with_forms'),
    path('month_with_forms/<int:year>/<int:month>/',
         views.MonthWithFormsCalendar.as_view(), name='month_with_forms'),

    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path('week_with_schedule/<int:year>/<int:month>/<int:day>/',
         views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),

    path('business_calendar/', views.BusinessCalendar.as_view(), name='business_calendar'),
    path('business_calendar/<int:year>/<int:month>/<int:day>/',
         views.BusinessCalendar.as_view(), name='business_calendar'),

    path('edit/<int:num>', views.edit, name='edit'),
    path('delete/<int:num>', views.delete, name='delete'),

]

sns/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('add', views.add, name='add'),
    path('creategroup', views.creategroup, name='creategroup'),
    path('post', views.post, name='post'),
    path('share/<int:share_id>', views.share, name='share'),
    path('good/<int:good_id>', views.good, name='good'),
]

mycalendar/models.py
import datetime
from pickle import FALSE
from django.db import models
from django.utils import timezone


# for schedule
class Schedule(models.Model):

    summary = models.CharField('Summary', max_length=50,null=True)
    description = models.TextField('details', blank=True)
    start_time = models.TimeField('start time', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('end time', default=datetime.time(7, 0, 0))
    date = models.DateField('date')
    created_at = models.DateTimeField('create date', default=timezone.now)

    def __str__(self):
        return self.summary + ',Schedule_ID:' +str(self.id) 

mycalendar/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    #Bootstrapに対応するためのModelForm

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time
        
class SimpleScheduleForm(forms.ModelForm):
    #シンプルなスケジュール登録用フォーム

    class Meta:
        model = Schedule
        fields = ('summary', 'date',)
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'date': forms.HiddenInput,
        }

mycalendar/views.py
import datetime
from pipes import Template
from sqlite3 import paramstyle
from traceback import StackSummary
from django.shortcuts import redirect, render
from django.views import generic
from .forms import BS4ScheduleForm, SimpleScheduleForm
from .models import Schedule
from . import mixins
from django.utils import timezone
import pytz


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    #月間カレンダーを表示するビュー
    template_name = 'mycalendar/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    #週間カレンダーを表示するビュー
    template_name = 'mycalendar/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context

class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    #スケジュール付きの週間カレンダーを表示するビュー
    template_name = 'mycalendar/week_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        context['week_row'] = zip(
            calendar_context['week_names'],
            calendar_context['week_days'],
            calendar_context['week_day_schedules'].values()
        )
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    #スケジュール付きの月間カレンダーを表示するビュー
    template_name = 'mycalendar/month_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context
    
class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.View):
    #フォーム付きの月間カレンダーを表示するビュー
    template_name = 'mycalendar/month_with_forms.html'
    model = Schedule
    date_field = 'date'
    form_class = SimpleScheduleForm
    

    def get(self, request, **kwargs):
        context = self.get_month_calendar()
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_month_calendar()
        formset = context['month_formset']
        if formset.is_valid():
            formset.save()
            return redirect('mycalendar:month_with_forms')

        return render(request, self.template_name, context)



class BusinessCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    #月間カレンダー、週間カレンダー、スケジュール登録画面付

    template_name = 'mycalendar/business_calendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context  



    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('mycalendar:business_calendar', year=date.year, month=date.month, day=date.day)
    
def edit(request, num):
    obj = Schedule.objects.get(id=num)
    if (request.method == 'POST'):
        schedule = BS4ScheduleForm(request.POST, instance=obj)
        schedule.save()
        return redirect(to='/mycalendar/business_calendar')
    params = {
        'title': 'Mycalendar',
        'id': num,
        'form': BS4ScheduleForm(instance=obj),
    }
    return render(request, 'mycalendar/edit.html', params)

def delete(request, num):
    obj = Schedule.objects.get(id=num)
    if (request.method == 'POST'):
        schedule = BS4ScheduleForm(request.POST, instance=obj)
        schedule.delete()
        return redirect(to='/business_calendar')
    params = {
        'title': 'Mycalendar',
        'id':num,
        'form': BS4ScheduleForm(instance=obj)
    }
    return render(request, 'mycalendar/delete.html', params)


def top(request):
    context = {
        'now': timezone.now(),
        'timzones': pytz.common_timezones,

    } 
    return render(request, 'mycalendar/top.html', context)
      

    
    

mycalendar/templates/mycalendar/base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
          
    <title>My Business Calendar</title>
</head>
<body>
<div>{% block header %}
        <p id="myid"></p>
        <script>
            t = 0;
            var elem = document.getElementById("myid");
     
            function myfunc(){
                var date = new Date();
                var hours = date.getHours();
                var minutes = date.getMinutes();
                var seconds = date.getSeconds();
                elem.innerHTML = hours+"時"+minutes+"分"+seconds+"秒" ;
            }
     
            t = setInterval("myfunc()", 500);
     
        </script>

        {% endblock %}</div>
<hr>
<div class="container" mt-3>
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <table class="table">
        <tr>
            <th>object</th>
        </tr>
    {% for }
    </table>
    <form action="{% url 'mycalendar:edit' id %}"
        method="post">

    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

mycalendar/templates/mycalendar/business_calendar.html
{% extends 'mycalendar/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'mycalendar/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'mycalendar/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                primaryColor:'#ff0033',
                textColor:'#330000',
                backgroundColor:'#ccffff',
                borderColor:'#3300cc',
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                primaryColor:'#ff0033',
                textColor:'#330000',
                backgroundColor:'#ccffff',
                borderColor:'#3300cc',
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

mycalendar/templates/mycalendar/delete.html
{% extends 'mycalendar/base.html' %}
{% block content %}
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <p>以下のレコードを削除します。</p>
    <table class="table">
        <tr><th>ID</th><td>{{obj.id}}</td></tr>
        
        <form action="{% url 'delete' id %}" method="post">
        {% csrf_token %}
        <tr><th></th><td>
            <input type="submit" value="click"
                class="btn btn-primary">
        </td></tr>
        </form>
    </table>

    
    
</body>
</html>

mycalendar/templates/mycalendar/edit.html
{% extends 'mycalendar/base.html' %}
{% block content %}
<body class="container">
    <h1 class="display-4 text-primary">
        {{title}}</h1>
    <form action="{% url 'mycalendar:edit' id %}"
        method="post">
    {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
            <tr><th><td>
                <input type="submit" value="click"
                    class="btn btn-primary mt-2">
            </td></th></tr>
        </table>
    </form>
    
</body>
{% endblock %}

mycalendar/templates/mycalendar/month.html
{% extends 'mycalendar/base.html' %}

{% block content %}
    <a href="{% url 'mycalendar:month' month_previous.year month_previous.month %}">Pre</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'mycalendar:month' month_next.year month_next.month %}">Next</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

mycalendar/templates/mycalendar/month_with_forms.html
{% extends 'mycalendar/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

    </style>

    <a href="{% url 'mycalendar:month_with_forms' month_previous.year month_previous.month %}">Pre</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'mycalendar:month_with_forms' month_next.year month_next.month %}">Next</a>

    <form action="" method="POST">
        {{ month_formset.management_form }}
        <table class="table">
            <thead>
            <tr>
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for week_day_forms in month_day_forms %}
                <tr>
                    {% for day, forms in week_day_forms.items %}
                        {% if now == day %}
                            <td class="table-success">
                                {% else %}
                            <td>
                        {% endif %}

                    <div>
                        {% if month_current.month != day.month %}
                            {{ day | date:"m/d" }}
                        {% else %}
                            {{ day.day }}
                        {% endif %}

                        {% for form in forms %}
                            {{ form.as_p }}
                        {% endfor %}

                        
                    </div>
                    </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

mycalendar/templates/mycalendar/month_with_schedule.html
{% extends 'mycalendar/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
    <a href="{% url 'mycalendar:month_with_schedule' month_previous.year month_previous.month %}">Pre</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'mycalendar:month_with_schedule' month_next.year month_next.month %}">Next</a>
    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                        <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>

        {% endfor %}

        </tbody>

    </table>
{% endblock %}

mycalendar/templates/mycalendar/top.html
{% extends 'mycalendar/base.html' %}
{% load tz %}

{% block content %}
{% for tz in timezones %}
    {{ tz}}: {{ now|timezone:tz}}
    <hr>
{% endfor %}

{% endblock %}

mycalendar/templates/mycalendar/week.html
{% extends 'mycalendar/base.html' %}
{% block content %}

    <a href="{% url 'mycalendar:week' week_previous.year week_previous.month  week_previous.day %}">Pre</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'mycalendar:week' week_next.year week_next.month  week_next.day %}">Next</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

mycalendar/templates/mycalendar/week_with_schedule.html
{% extends 'mycalendar/base.html' %}
{% block content %}

    <a href="{% url 'mycalendar:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">Pre</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'mycalendar:week_with_schedule' week_next.year week_next.month  week_next.day %}">Next</a>

    <table class="table table-bordered">
        <tbody>
        {% for week_name, day, schedules in week_row %}
            <tr>
                <td>
                    {% if week_first.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}
                    ({{ week_name }})
                </td>

                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}